name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode"
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - run: docker container run --volume="$(pwd)":/app "${IMAGE_NAME}" npm run lint 
      # - run: docker container run "${IMAGE_NAME}" npm run lint